### ISSUE TITLE
Elasticsearch cluster rejects signature when RestClientBuilder.setCompressionEnabled() is set

### ISSUE THREAD

**Issue by cykl** [awslabs/aws-request-signing-apache-interceptor#10]
Elasticsearch client recently introduced [RestClientBuilder.setCompressionEnabled()](https://github.com/elastic/elasticsearch/pull/63230) enabling request and response compression. Before that, one could enable response compression using `builder.setDefaultHeaders( new Header[ ] { new BasicHeader( HttpHeaders.ACCEPT_ENCODING, "gzip" ) } );` but not request compression.

I just tried to enable to enable compression and cluster started to reject requests because of signature mismatch

```
ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [POST], host [https://my-cluster.eu-west-3.es.amazonaws.com], URI [/_bulk?timeout=1m], status line [HTTP/1.1 403 Forbidden]
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}];
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1891)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1645)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1602)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1572)
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:537)
	at xxx.Injector.sendBulkRequest(Injector.java:181)
	at xxx.Injector.lambda$run$0(Injector.java:141)
	at xxx.SynchronousRetry.execute(SynchronousRetry.java:29)
	at xxx.Injector.run(Injector.java:141)
	at xxx.Injector.main(Injector.java:75)
	Suppressed: ParsingException[Failed to parse object: expecting field with name [error] but found [message]]
		at org.elasticsearch.common.xcontent.XContentParserUtils.ensureFieldName(XContentParserUtils.java:49)
		at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:592)
		at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:179)
		at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1911)
		at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1888)
		... 10 more
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [https://my-cluster.eu-west-3.es.amazonaws.com], URI [/_bulk?timeout=1m], status line [HTTP/1.1 403 Forbidden]
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632)
	... 9 more
```

I haven't had time to troubleshoot it yet but was able to check that `signableRequest.setContent( httpEntityEnclosingRequest.getEntity( ).getContent( ) );` returns a gziped stream which is what I had expect.

**Comment by cykl** [comment]
@swallez Do you have an idea?

**Comment by swallez** [comment]
`Failed to parse object: expecting field with name [error] but found [message]]` indicates that the JSON is correct from a syntax perspective, but does not match the expected format. So unlikely to be related to gzip.

**Comment by swallez** [comment]
BTW I don't understand how this is related to this AWS project...

**Comment by cykl** [comment]
Amazon Elasticsearch Service relies on [Signature Version 4 signing process](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) for authorisation. Basically, request is signed using a private key and the signature is added to request headers. See also, https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html.

This project provides an HttpRequestInterceptor implementing the Sigv4 signing process which can be added to the RestClient:

```java
      HttpRequestInterceptor interceptor =
                new AwsRequestSigningApacheInterceptor( SERVICE_NAME, signer, credentialsProvider );

        restClientBuilder.setHttpClientConfigCallback( hacb -> hacb.addInterceptorLast( interceptor ) );
```

Amazon Elasticsearch Service accepts requests signed by this interceptor & org.elasticsearch.client:elasticsearch-rest-high-level-client:7.10.1. If `setCompressionEnabled()` is invoked, requests are rejected. 

I can think of two causes:

 1. Signature should be performed on uncompressed signature but `httpEntityEnclosingRequest.getEntity( ).getContent( )` now returns the compressed entity. If so, this project must be fixed to handle compression
 1. Something differs between what AwsRequestSigningApacheInterceptor captures to compute the signature and what is sent.

I hope this clarify the issue.

I will investigate 1.

**Comment by cykl** [comment]
I quickly tried to provide an uncompressed stream to the Signer using

```java
                var entity = ( RestClient.ContentCompressingEntity ) httpEntityEnclosingRequest.getEntity( );
                var bais = new ByteArrayInputStream( new GZIPInputStream( entity.getContent( ) ).readAllBytes( ) );
                signableRequest.setContent( bais );
``` 

It didn't fix the issue. I guess we need to carefully read Sigv4 documentation or SDK documentation. 

@cheruvian Is this repo still maintained? Could someone comfortable with SigV4 provide assistance?
